import { OBJ_TYPE } from '../../common/constants/common';

export enum GET_SORT_OBJECT_TYPE {
  VTODO = OBJ_TYPE.VTODO
}

export enum SORT_OBJECT_TYPE {
  VTODO = OBJ_TYPE.VTODO,
  URL = OBJ_TYPE.URL,
  CSFILE = OBJ_TYPE.CSFILE,
  KANBAN = OBJ_TYPE.KANBAN,
  CANVAS = OBJ_TYPE.CANVAS
}

export const GET_SORT_OBJECT_TYPES = [SORT_OBJECT_TYPE.VTODO];

export const SORT_OBJECT_TYPES = [SORT_OBJECT_TYPE.VTODO, SORT_OBJECT_TYPE.URL,
  OBJ_TYPE.CSFILE, SORT_OBJECT_TYPE.KANBAN, SORT_OBJECT_TYPE.CANVAS];

export const SORT_OBJECT = {
  MAX_ORDER_NUMBER: 999999,
  MIN_ORDER_NUMBER: -999999,
  MAX_ORDER_NUMBER_LENGTH: 10,
  ORDER_UPDATE_TIME_INIT: 0.001
};
