CREATE TABLE `access_token` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `app_id` varchar(255) NOT NULL,
  `device_uid` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `access_token` tinyblob NOT NULL,
  `access_token_iv` tinyblob NOT NULL,
  `refresh_token` tinyblob NOT NULL,
  `refresh_token_iv` tinyblob NOT NULL,
  `previous_refresh_token` tinyblob,
  `scope` text,
  `token_type` varchar(45) NOT NULL,
  `user_agent` varchar(255) DEFAULT '',
  `ip` varchar(45) DEFAULT '',
  `is_revoked` tinyint(1) unsigned DEFAULT '0',
  `device_token` varchar(255) DEFAULT NULL,
  `expires_in` double NOT NULL,
  `expires_in_refresh_token` double NOT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_on_device_uid_and_access_token` (`device_uid`,`access_token`(255)) USING BTREE,
  UNIQUE KEY `uniq_on_device_uid_and_refresh_token` (`device_uid`,`refresh_token`(255)) USING BTREE,
  UNIQUE KEY `uniq_access_token_iv` (`access_token_iv`(64)) USING BTREE,
  UNIQUE KEY `uniq_refresh_token_iv` (`refresh_token_iv`(64)) USING BTREE,
  KEY `idx_on_app_id_and_device_uid` (`app_id`,`device_uid`) USING BTREE,
  KEY `idx_on_user_id_and_app_id_and_device_uid` (`user_id`,`app_id`,`device_uid`) USING BTREE,
  KEY `idx_on_is_revoked_and_device_uid_and_access_token` (`is_revoked`,`device_uid`,`access_token`(255)) USING BTREE,
  KEY `idx_email` (`email`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_app_id` (`app_id`),
  KEY `idx_expires_in` (`expires_in`),
  KEY `access_token_device_token_IDX` (`device_token`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC COMMENT='latin1_swedish_ci'