CREATE TABLE `card_contact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varbinary(1000) DEFAULT NULL,
  `addressbookid` int(11) NOT NULL,
  `card_id` int(11) unsigned DEFAULT NULL,
  `uri` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `midle_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_address` json DEFAULT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_avatar` text COLLATE utf8mb4_unicode_ci,
  `phone` json DEFAULT NULL,
  `skype_call` json DEFAULT NULL,
  `skype_chat` json DEFAULT NULL,
  `vip` tinyint(1) unsigned DEFAULT '0',
  `is_group` tinyint(1) unsigned DEFAULT '0',
  `trashed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_idx_card_contact_uid_addressbookid` (`uid`,`addressbookid`) USING BTREE,
  KEY `idx_is_trashed` (`trashed`),
  KEY `idx_cardcontact_uid` (`uid`),
  KEY `idx_cardcontact_addressbookid_uri` (`addressbookid`,`uri`),
  KEY `fk_card_contact_uid_addressbookid` (`card_id`) USING BTREE,
  CONSTRAINT `fk_card_contact_uid_addressbookid` FOREIGN KEY (`card_id`) REFERENCES `cards` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci