CREATE TABLE `linked_collection_object` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `collection_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `object_uid` varbinary(1000) NOT NULL,
  `object_type` varbinary(50) NOT NULL,
  `object_href` text COLLATE utf8mb4_unicode_ci,
  `is_trashed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `email_time` double(13,3) DEFAULT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`collection_id`,`account_id`,`object_uid`),
  KEY `idx_id_inc` (`id`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_account_collection_object` (`collection_id`,`account_id`,`object_type`,`object_uid`),
  KEY `idx_user_collection_object` (`collection_id`,`user_id`,`object_type`),
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_object_uid` (`object_uid`),
  KEY `idx_on_user_id_and_account_id` (`user_id`,`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci