CREATE TABLE `trash_collection` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `object_id` bigint(20) unsigned DEFAULT NULL,
  `object_uid` varbinary(1000) DEFAULT NULL,
  `object_type` varbinary(50) NOT NULL,
  `object_href` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `sync_token` tinyint(2) unsigned DEFAULT '0',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `trash_time` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id_and_object_uid_and_object_type` (`user_id`,`object_uid`,`object_type`) USING BTREE,
  UNIQUE KEY `user_id_and_object_id_and_object_type` (`user_id`,`object_id`,`object_type`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_object_type` (`object_type`) USING BTREE,
  KEY `idx_on_object_type_and_object_type` (`object_uid`,`object_type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci'