CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `digesta1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `digestb` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `domain_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `appreg_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fullname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rsa` text COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `secondary_email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `birthday` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `gender` tinyint(1) NOT NULL DEFAULT '0',
  `country` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `phone_number` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `country_code` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `token` varchar(500) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `token_expire` double(13,3) NOT NULL DEFAULT '0.000',
  `question` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `answer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active_sec_email` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `max_uid` int(20) NOT NULL DEFAULT '0',
  `activated_push` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `quota_limit_bytes` bigint(20) unsigned NOT NULL DEFAULT '0',
  `disabled` tinyint(1) NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_username` (`username`),
  KEY `idx_domain_id` (`domain_id`),
  KEY `idx_email` (`email`) USING BTREE,
  KEY `idx_on_token_and_token_expire` (`token`,`token_expire`),
  FULLTEXT KEY `idx_username` (`username`),
  FULLTEXT KEY `idx_fulltext_email` (`email`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`domain_id`) REFERENCES `virtual_domain` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='utf8_unicode_ci'