source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.1'

gem 'daemons', '1.3.1'
gem 'houston', '2.4.0'
gem 'mysql2', '0.5.2'
gem 'rufus-scheduler', '3.5.2'
gem 'tzinfo-data'
