export const DEL_USER_PROGRESS = {
  not_yet: 0,
  doing_db: 1,
  done_db: 2,
  done: 3
};

export const CONN_EXP_NAME = 'db_export';

export const MAX_RECORD_SELECT = 500;

export enum DELETED_ITEM_TYPE {
  CANVAS = 'CANVAS'
  , CSFILE = 'CSFILE'
  , FILE = 'FILE'
  , FILE_MEMBER = 'FILE_MEMBER'
  , FOLDER = 'FOLDER'      // colections
  , FOLDER_MEMBER = 'FOLDER_MEMBER'      // shared colections
  , HISTORY = 'HISTORY'
  , KANBAN = 'KANBAN'
  , LINK = 'LINK'
  , COLLECTION_LINK = 'COLLECTION_LINK'
  , COLLECTION_LINK_MEMBER = 'COLLECTION_LINK_MEMBER'
  , ORDER_OBJ = 'ORDER_OBJ'
  , SET_3RD_ACC = 'SET_3RD_ACC'
  , SUGGESTED_COLLECTIONTRACK = 'SUGGESTED_COLLECTIONTRACK'
  , TRASH = 'TRASH'
  , URL = 'URL'
  , VCARD = 'VCARD'
  , VCARD_AVATAR = 'VCARD_AVATAR'
  , VEVENT = 'VEVENT'
  , VJOURNAL = 'VJOURNAL'
  , VTODO = 'VTODO'
  , TRACK = 'TRACK'
  , METADATA_EMAIL = 'METADATA_EMAIL'
  , NOTE = 'NOTE'
  , CALENDAR = 'CALENDAR'
  , CALENDAR_INSTANCE = 'CALENDAR_INSTANCE'
  , ADDRESS_BOOK = 'ADDRESS_BOOK'
  , RECENT_OBJ = 'RECENT_OBJ'
  , VIDEO_CALL = 'VIDEO_CALL'
  , MEMBER = 'SHARE_MEMBER'
  , SYSTEM_COLLECTION = 'SYSTEM_COLLECTION'
  , MANUAL_RULE = 'MANUAL_RULE'
  , COLLECTION_INSTANCE_MEMBER = 'COLLECTION_INSTANCE_MEMBER'
  , SUGGESTED_COLLECTION = 'SUGGESTED_COLLECTION'
}