################# For API ####################
API_SUCCESS = 0       #success for anything
API_USER_EXISTED = 1
API_USER_NOT_EXISTED = 2
API_PASS_INVALID = 3
API_USER_INVALID = 4

API_APPREG_INVALID = 5
API_TOKEN_EXPIRED = 6
API_SIG_INVALID = 7
API_SEC_EMAIL_INVALID = 8

API_ITEM_NOT_EXIST = 9
API_ITEM_CANNOT_SAVE = 10
API_ITEM_CANNOT_DELETE = 11

API_ITEM_NO_URI = 12

#error code for subscription
API_RECEIPT_DATA_EXISTED = 13
API_RECEIPT_DATA_FAILED = 14
API_TRANSACTION_INVALID = 15
API_RECEIPT_DATA_INVALID = 16
API_TRANSACTION_EXISTED = 17

API_USER_DISABLED = 18 #will be disabled after 90 days if user does not upgrade account

CAN_NOT_DOWNLOAD = 19

FILE_NOT_FOUND = 20
INVALID_RECORD = 21
RECORD_NOT_FOUND = 22
UNAUTHORIZED = 23
UPLOAD_FAILED = 24
PARAMETER_MISSING = 25
EMAIL_NOT_ALLOWED_CODE = 26
NOT_AUTHORIZED = 27
CAN_NOT_ADD_THIRD_PARTY = 28
OVER_LIMITED_PARAMS= 29

UNEXPECTED_ERROR = 500
ICLOUD_USER_INVALID = 64
YAHOO_USER_INVALID = 128
CARDDAV_USER_INVALID = 256
################# For Web ####################
