source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.1'

gem 'rails', '5.2.2.1'
gem 'mysql2', '0.4.4'

gem 'ice_cube', '0.7.6'
gem 'ri_cal','0.8.8'
gem 'tzinfo'#, "0.3.37"
# gem "aes", "~> 0.5.0"
gem 'uuid', '2.3.8'
gem 'vcard', '~> 0.2.0'
gem 'color', '1.8'
gem 'mail', '2.5.5'
gem "auto_html", '2.0.0'

gem 'invert','0.1.0' #sort multiple attributes
# gem 'pismo','0.7.4'
gem 'metainspector', '~> 5.6'

gem 'net-http-digest_auth','1.4.1'
gem 'icalendar', '2.0.1'
gem 'vpim', '13.11.11'
# gem 'aescrypt','1.0.0'
gem 'httparty', '0.14.0'
gem 'clamp', '1.1.2'
gem 'highline', '1.7.8'
gem 'jwt','1.5.6'
gem 'geocoder','1.4.3'


gem 'rumoji', '0.5.0'
gem 'gemoji-parser', '1.3.1'

gem 'daemons', '1.2.4'
gem 'dalli', '2.7.6' #cache data
#gem 'agcaldav'
gem 'nokogiri','1.10.7'
gem 'httpclient', '2.8.3'
gem 'will_paginate', '3.1.5'

gem 'silencer','1.0.0'

gem "rest-client",'1.8.0'
gem 'date_diff', '0.0.4'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '2.6.4'

gem 'browser', '1.1.0'

gem 'faraday', '~> 0.10'

gem 'rack-cors', '1.0.5', :require => 'rack/cors'

gem 'pundit', '2.0.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'redis'

# Background Job
gem "resque", '2.0.0'
gem "resque-scheduler", '4.4.0'
gem "sidekiq", '~> 5.2.7'
gem "sidekiq-status"

# resize image contact
gem "mini_magick", '4.9.4'
group :production do
  gem 'logging-rails', :require => 'logging/rails'
  gem 'lograge'
  gem 'ddtrace'
end

group :development do
  # Use Puma as the app server
  gem 'puma', '~> 3.12.2'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
  gem 'pry-byebug'
end

group :development, :test do
  gem 'awesome_print', '~> 1.8.0'
  gem 'bullet', '~> 5.9.0'
  gem 'dotenv-rails'
  gem 'factory_bot_rails', '~> 4.8.2'
  gem 'faker', '~> 1.6.6'
  gem 'ffaker', '~> 2.2.0'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.8.1'
  gem 'rubocop', '~> 0.49.1', require: false
  gem 'rubocop-rspec', '~> 1.5.0'
  gem 'rails-perftest', :git => 'git://github.com/rails/rails-perftest.git'
  gem 'ruby-prof'
  gem 'test-unit'
end

group :test do
  gem 'database_cleaner', '~>1.6.2'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
