module.exports = {
  REGION: process.env.AWS_REGION,
  ACCOUNT_ID: process.env.AWS_ACCOUNT_ID,
  API_VERSION: process.env.AWS_API_VERSION,

  // Queue Name
  SQS_URL_DOVECOT_NEW_MAIL: process.env.SQS_URL_DOVECOT_NEW_MAIL,
  DOVECOT_LINKED_MAIL_COLLECTION: process.env.DOVECOT_LINKED_MAIL_COLLECTION,
  DOVECOT_LINKED_MAIL_COLLECTION_JOB: process.env.DOVECOT_LINKED_MAIL_COLLECTION_JOB,
  DELETE_MAIL_TRIGGER_QUEUE: process.env.RABBITMQ_DELETE_MAIL_TRIGGER_QUEUE,
  DELETE_MAIL_TRIGGER_JOB: process.env.RABBITMQ_DELETE_MAIL_TRIGGER_JOB
};
