CREATE TABLE `collection` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `calendar_uri` varchar(255) COLLATE utf8_unicode_ci DEFAULT '0',
  `parent_id` bigint(20) DEFAULT '0',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` tinyint(1) NOT NULL DEFAULT '0',
  `info_card_order` int(11) NOT NULL DEFAULT '0',
  `current_mode` int(11) NOT NULL DEFAULT '0',
  `alerts` json DEFAULT NULL,
  `order_storyboard` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `order_kanban` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `state` tinyint(1) unsigned DEFAULT '1',
  `flag` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_hide` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_expand` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `view_mode` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `view_sort` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kanban_mode` tinyint(1) DEFAULT '0',
  `icon` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Icon shortcut from table collection_icon',
  `due_date` double(13,3) DEFAULT '0.000',
  `recent_time` double(13,3) NOT NULL DEFAULT '0.000',
  `is_trashed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_is_trashed` (`is_trashed`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_calendar_id` (`calendar_uri`) USING BTREE,
  KEY `idx_on_user_id_and_parent_id` (`user_id`,`parent_id`) USING BTREE,
  KEY `idx_on_id_and_user_id` (`id`,`user_id`) USING BTREE,
  KEY `idx_type` (`type`) USING BTREE,
  FULLTEXT KEY `idx_collection_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'