CREATE TABLE `conference_member` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `channel_id` bigint(20) unsigned NOT NULL,
  `uid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_creator` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `title` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `avatar` text COLLATE utf8mb4_unicode_ci,
  `vip` tinyint(1) NOT NULL DEFAULT '0',
  `chat_url` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `member_arn` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `revoke_time` double(13,3) NOT NULL DEFAULT '0.000',
  `join_time` double(13,3) DEFAULT '0.000',
  `view_chat_history` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_on_conference_id_and_user_id_and_user_name` (`channel_id`,`user_id`,`email`) USING BTREE,
  KEY `idx_user_id` (`user_id`),
  KEY `idx_channel_id` (`channel_id`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_revoke_time` (`revoke_time`) USING BTREE,
  KEY `idx_email` (`email`),
  KEY `conference_member_vip_IDX` (`vip`) USING BTREE,
  KEY `idx_vip` (`vip`),
  FULLTEXT KEY `conference_member_member_arn_IDX` (`member_arn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'