CREATE TABLE `third_party_account` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `server_income` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `user_income` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pass_income` varchar(1000) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `port_income` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `use_ssl_income` int(11) DEFAULT '0',
  `type_income` int(11) DEFAULT '0',
  `server_smtp` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_smtp` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `pass_smtp` varchar(1000) COLLATE utf8_unicode_ci DEFAULT '',
  `port_smtp` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `use_ssl_smtp` int(11) NOT NULL DEFAULT '0',
  `auth_type_smtp` int(11) NOT NULL DEFAULT '0',
  `server_caldav` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `server_path_caldav` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `port_caldav` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `use_ssl_caldav` int(11) DEFAULT '0',
  `use_kerberos_caldav` int(11) DEFAULT '0',
  `auth_type` int(11) DEFAULT '0',
  `account_type` int(11) DEFAULT '0',
  `account_sync` json DEFAULT NULL,
  `auth_key` text COLLATE utf8_unicode_ci,
  `auth_token` text COLLATE utf8_unicode_ci,
  `full_name` varchar(255) CHARACTER SET utf8mb4 DEFAULT '',
  `description` varchar(255) CHARACTER SET utf8mb4 DEFAULT '',
  `refresh_token` text COLLATE utf8_unicode_ci NOT NULL,
  `provider` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `icloud_user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `third_party_user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `user_caldav` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `email_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `token_expire` int(11) DEFAULT '0',
  `activated_push` int(11) NOT NULL DEFAULT '0',
  `signature` text CHARACTER SET utf8mb4 NOT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_on_user_id_and_user_income_and_account_type` (`user_id`,`user_income`,`account_type`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'