// REAL TIME SERVICE
export const EVENT_TO_INDIVIDUAL = 'EVENT_TO_INDIVIDUAL';

export const NOTIFICATION_TO_INDIVIDUAL = 'NOTIFICATION_TO_INDIVIDUAL';

export const EVENT_TO_CHANNEL = 'EVENT_TO_CHANNEL';

export const NOTIFICATION_TO_CHANNEL = 'NOTIFICATION_TO_CHANNEL';

export const CREATE_REALTIME_CHANNEL = 'CREATE_REALTIME_CHANNEL';

export const DELETE_REALTIME_CHANNEL = 'DELETE_REALTIME_CHANNEL';

export const REMOVE_MEMBER_FROM_CHANNEL = 'REMOVE_MEMBER_FROM_CHANNEL';

export const ADD_MEMBER_TO_CHANNEL = 'ADD_MEMBER_TO_CHANNEL';
// MEETING
export const START_MEETING = 'START_MEETING';
export const END_MEETING = 'END_MEETING';
export const END_MEETING_FROM_API = 'END_MEETING_FROM_API';
// CONFERENCE
export const ADD_ATTENDEE_TO_MEETING = 'ADD_ATTENDEE_TO_MEETING';
export const REMOVE_ATTENDEE_FROM_MEETING = 'REMOVE_ATTENDEE_FROM_MEETING';
export const JOIN_ATTENDEE_TO_MEETING = 'JOIN_ATTENDEE_TO_MEETING';
export const LEAVE_ATTENDEE_FROM_MEETING = 'LEAVE_ATTENDEE_FROM_MEETING';
