export enum API_LAST_MODIFIED_NAME {
  USER = 'user',
  SETTING = 'setting',
  THIRD_PARTY_ACCOUNT = 'third_party_account',
  COLLECTION = 'collection',
  KANBAN = 'kanban',
  FILE = 'file',
  KANBAN_CARD = 'kanban_card',
  CLOUD = 'cloud',
  CREDENTIAL = 'credential',
  PLATFORM_SETTING = 'platform_setting',
  URL = 'url',
  URL_MEMBER = 'url_member',
  RECENT_OBJECT = 'recent_object',
  CONTACT_HISTORY = 'contact_history',
  /**
   * @deprecated
   */
  SORT_OBJECT = 'sort_object',
  LINKED_OBJECT = 'linked_object',
  LINKED_COLLECTION_OBJECT = 'linked_collection_object',
  LINKED_COLLECTION_OBJECT_MEMBER = 'linked_collection_object_member',
  EMAIL_TRACKING = 'email_tracking',
  TRASH = 'trash',
  CALENDAR = 'calendar',
  TODO = 'todo',
  NOTE = 'note',
  EVENT = 'event',
  ADDRESSBOOK = 'addressbook',
  CONTACT = 'contact',
  METADATA_EMAIL = 'metadata_email',
  SYSTEM_COLLECTION = 'system_collection',
  SUBSCRIPTION = 'subscription',
  CONFERENCING = 'conferencing',
  CONFERENCE_MEMBER = 'conference_member',
  OWNER_SHARE_MEMBER = 'share_member',
  SHARE_MEMBER_MEMBER = 'share_member_member',
  COLLECTION_MEMBER = 'collection_member',
  COLLECTION_ACTIVITY = 'collection_activity',
  CONFERENCE_CHAT = 'conference_chat',
}