module.exports = {
    REGION: process.env.AWS_REGION,
    ACCOUNT_ID: process.env.AWS_ACCOUNT_ID,
    API_VERSION: process.env.AWS_API_VERSION,
    KEY_MAP_PUSH_NOTIFY: process.env.KEY_MAP_PUSH_NOTIFY ? JSON.parse(process.env.KEY_MAP_PUSH_NOTIFY) : '',
    // Queue Name
    AUTO_WATCH_GMAIL: process.env.AUTO_WATCH_GMAIL_QUEUE_NAME,
    REGISTER_PUSH_GMAIL: process.env.REGISTER_PUSH_GMAIL_QUEUE_NAME,
    HANDLE_WEBHOOK_GMAIL: process.env.HANDLE_WEBHOOK_GMAIL_QUEUE_NAME,
    DOVECOT_NEW_MAIL: process.env.DOVECOT_NEW_MAIL_QUEUE_NAME,
    AWS_SQS_SIGNUP_QUEUE_NAME: process.env.AWS_SQS_SIGNUP_QUEUE_NAME,
    SORT_OBJECT_QUEUE_NAME: process.env.SORT_OBJECT_QUEUE_NAME
};

