import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEmail,
  IsNotEmpty, IsString
} from 'class-validator';
import { IsOptionalCustom } from '../../../common/decorators';

export class GetDownloadDto {
  @ApiProperty({
    description: "It is ID of file which stored in HDD (it will be generated by server side)"
  })
  @IsString()
  @IsNotEmpty()
  uuid: string;

  @ApiProperty({
    description: "The value contains the downloaded subFolder information"
  })
  @IsString()
  @IsNotEmpty()
  type: string;

  @ApiPropertyOptional({
    description: "User's email"
  })
  @IsEmail()
  @IsOptionalCustom()
  email: string;
}