module.exports = {
  EXPIRE_TIME:
    process.env.EXPIRE_TIME_ACCESS_TOKEN ? Number(process.env.EXPIRE_TIME_ACCESS_TOKEN) : 14400, // 4h, 14400s

  ACCESS_TOKEN_EXPIRE_TIME:
    process.env.EXPIRE_TIME_ACCESS_TOKEN ? Number(process.env.EXPIRE_TIME_ACCESS_TOKEN) : 14400, // 60 * 60 * 4 >> 4h
  REFRESH_TOKEN_EXPIRE_TIME:
    process.env.EXPIRE_TIME_REFRESH_TOKEN ? Number(process.env.EXPIRE_TIME_REFRESH_TOKEN) : 15552000, // 60 * 60 * 24 * 30 * 6 >> expire 6 month
  MAIN_KEY_CACHE: 'OAuth',
  AUTHORIZATION_KEY_CACHE: 'Authorization',
  MIGRATED_PLATFORM_KEY_CACHE: 'Migrate_Flatform',
  BUILD_VERSION_MATCHER: /build ([\d.]+)/,
  MAC_VERSION_MATCHER: /Mac OS X Version ([\d.]+)/,
  IOS_VERSION_MATCHER: /iOS Version ([\d.]+)/,
  BROWSER_VERSION_MATCHER: /([\d]+.[\d])/,
  FLO_VERSION_MATCHER: /Flo\/([\d.]+)/,
  DEVICE_MODEL_MATCHER: /Device ([\s\w,.]+)/,
  SALT_ROUNDS: 10,
  FLO_ONLINE_ACCESS_TOKEN_LIMITED: 10,
  ACCESS_TOKEN_LENGTH_IN_BYTE: 32,
  ACCESS_TOKEN_LENGTH: 64,
  REFRESH_TOKEN_LENGTH_IN_BYTE: 32,
  REFRESH_TOKEN_LENGTH: 64,
  TTL_OVERDUE: 10,
  TOKEN_TYPE: 'Bearer',
  TIMEZONE: 'America/Chicago',
  COMPONENTS: 'VEVENT,VTODO,VJOURNAL,VFREEBUSY,VALARM',
  AES_KEY: process.env.FLO_AES_KEY,
  AES_ALGORITHM: 'aes-256-cbc',
  SALT_LENGTH: -16,
  IV_LENGTH: 32,
  IV_LENGTH_IN_BYTE: 16,
  USERNAME_LENGTH_ALLOW: [3, 32],
  DEVICE_UID_LENGTH_ALLOW: [10, 50],
  FLO_EMAIL_DOMAIN: process.env.FLO_EMAIL_DOMAIN,
  SERVICE_HEALTH_CHECK_TIMEOUT:
    process.env.SERVICE_HEALTH_CHECK_TIMEOUT ? Number(process.env.SERVICE_HEALTH_CHECK_TIMEOUT) : 1000,
  JOI_ALLOW_UNKNOWN: process.env.JOI_ALLOW_UNKNOWN ? process.env.JOI_ALLOW_UNKNOWN.toLocaleLowerCase() === 'true' : true,
  INTERNAL_MAIL_URL: process.env.INTERNAL_MAIL_URL,
  INTERNAL_MAIL_REQUEST_TIMEOUT: process.env.INTERNAL_MAIL_REQUEST_TIMEOUT ? Number(process.env.INTERNAL_MAIL_REQUEST_TIMEOUT) : 10000,
  USER_MIGRATE_STATUS: {
    NOT_FOUND_USER: 0,
    NOT_MIGRATE: 1,
    MIGRATED: 2,
    MIGRATING: 3,
    INIT_MIGRATE: 4,
    MIGRATE_FAILED: -1
  },
  USER_REVERT_MIGRATE_STATUS: {
    NOT_FOUND_USER: 0,
    NOT_MIGRATE: 1,
    MIGRATED: 2,
    REVERTING: 3
  },
  USER_DATA_MIGRATE_QUEUE: 'userDataMigrateQueue_v4_1',
  USER_MIGRATE_DATA_JOB: 'UserMigrateDataJob',
  USER_MIGRATE_DATA_JOB_TTL: 1800, // 30 minutes,
  USER_MIGRATE_DATA_CACHE: 'FLO_OAUTH_MIGRATE_DATA_USER_',
  USER_REVERT_MIGRATE_DATA_CACHE: 'FloBackendAdmin:admin_revert_user_data:',
  FLO_RESTRICTED_RULE: 'FloBackendAdmin:restrictedRule',
  FLO_RESTRICTED_RULE_TTL: 600, // 10 minutes,
  REVERT_USER_DATA_QUEUE: 'revertDataMigrateUserQueue_v4_1',
  REVERT_DATA_USER_JOB: 'RevertDataMigrateUserJob',
  REPORT_CACHED_USER_QUEUE: 'reportCachedUserQueue',
  INTERNAL_GROUP: '2'

};
