module.exports = {
  INVALID_OR_MISSING_USERNAME: 'Invalid or missing username',
  LOGIN_FAILED_USERNAME_OR_PASSWORD_INVALID: 'Login failed. Username or password invalid',
  YOUR_ACCOUNT_HAS_BEEN_DISABLED_PLEASE_CONTACT_YOUR_ADMINISTRATOR: 'Your account has been disabled. Please contact your administrator.',
  EMAIL_FORMAT_IS_NOT_VALID: 'Invalid email format',
  USERNAME_MUST_BE_A_VALID_EMAIL: 'username must be a valid email',
  EMAIL_IS_RESTRICTED: 'Email is restricted',
  USER_ALREADY_EXIST: 'User already exist',
  INVALID_PASSWORD: 'Invalid password',
  INVALID_EMAIL: 'Invalid email',
  INVALID_TIMEZONE: 'Invalid timezone',
  INVALID_DATA: 'Invalid data',
  INVALID_REFRESH_TOKEN_INFORMATION: 'Invalid refresh token information',
  INVALID_ACCESS_TOKEN_INFORMATION: 'Invalid access token information',
  REVOKE_ACCESSTOKEN_FAILED: 'Revoke accesstoken failed',
  THE_TOKEN_IS_REVOKED: 'The token is revoked',
  REFRESH_TOKEN_HAS_EXPIRED: 'Refresh Token has expired',
  ACCESS_TOKEN_STILL_HAS_UPTIME: 'Access Token still has uptime',
  USER_INFORMATION_DOES_NOT_EXIST: 'User information does not exist',
  REFRESH_TOKEN_FAILED: 'Refresh Token failed',
  INVALID_ACCOUNT_INFORMATION: 'Invalid account information',
  INVALID_TOKEN_OR_ALREADY_EXPIRED: 'Invalid token or already expired',
  PASSWORD_HAS_BEEN_RESET_SUCCESSFULLY: 'Password has been reset successfully',
  ACCOUNT_HAS_BEEN_DISABLED: 'Account has been disabled',
  REQUEST_SUCCESSFULLY: 'Request successfully',
  PASSWORDS_LENGTH_MUST_HAVE_A_MINIMUM_OF_6_AND_A_MAXIMUM_OF_32_CHARACTERS_RESPECTIVELY: 'Passwords length must have a minimum of 6 and a maximum of 32 characters respectively',
  LOGIN_FAILED: 'Login failed',
  SYSTEM_ERROR: 'System error',
  REQUEST_FAIL: 'Request fail',
  UNKNOWN_DEVICE: 'Unknown Device',
  CREATE_USER_FAIL: 'Create user fail',
  CREATE_USER_SUCCESS: 'Create user success',
  GENERATE_CALENDARS_FAIL: 'Generate calendars fail',
  GENERATE_COLLECTIONS_FAIL: 'Generate collections fail',
  GENERATE_DEFAULT_SETTING_FAIL: 'Generate default setting fail',
  GENERATE_SYSTEM_KANBAN_FAIL: 'Generate system kanban fail',
  SERVICE_STATUS_MONITOR: 'Service status monitor',
  SENDING_THE_CREDENTIALS_TO_AUTHORIZATION_SERVER_HEADERS_APPID_DEVICEUID: 'Sending the credentials to authorization server (Headers:  AppId, DeviceUid)',
  REGISTER_NEW_USER_INFORMATION_DESCRIPTION: `Register new user information (Headers: AppId, DeviceUid) \n
  Note !! SignUp API will auto generate : \n
  Calendar, Project, Setting, Kanban. Worker will handle the rest init data such as Bookmark, address, url,... `,
  THE_API_IS_USED_TO_RETURN_NEW_ACCESSTOKEN_INFORMATION_AND_NEW_REFRESHTOKEN_HEADERS_APPID_DEVICEUID: 'The API is used to return new accessToken information and new refreshToken. (Headers: AppId, DeviceUid)',
  REVOKE_DATA_ACCESS_HEADERS_APPID_DEVICEUID_AUTHORIZATION: 'Revoke data access (Headers: AppId, DeviceUid, Authorization)',
  CHANGE_PASSWORD_OF_USER_HEADERS_APPID_DEVICEUID_AUTHORIZATION: 'Change password of the user (Headers: AppId, DeviceUid, Authorization)',
  RESET_PASSWORD_OF_USER_HEADERS_APPID_DEVICEUID: 'Reset password of the user (Headers: AppId, DeviceUid)',
  CHECK_THE_EXISTENCE_OF_EMAIL_HEADERS_APPID_DEVICEUID: `Check the existence of email (Headers: AppId, DeviceUid)
  If checking email is exists -> This email already exists. \n * If checking email does not exist -> It appears that the email address is not registered with us`,
  THIS_EMAIL_ALREADY_EXISTS: 'This email already exists',
  IT_APPEARS_THAT_THE_EMAIL_ADDRESS_IS_NOT_REGISTERED_WITH_US: 'It appears that the email address is not registered with us',
  UNAUTHORIZED_AUTHORIZATION_INFO_IS_UNDEFINED_OR_THE_WRONG_FORMAT: 'Unauthorized. Authorization info is undefined or the wrong format',
  UNAUTHORIZED: 'Unauthorized',
  APP_ID_IS_REQUIRED: 'app_id is required',
  DEVICE_UID_IS_REQUIRED: 'device_uid is required',
  INVALID_APP_ID: 'Invalid app_id',
  INVALID_DEVICE_UID: 'Invalid device_uid',
  INVALID_AUTHORIZATION: 'Invalid authorization',
  AUTHENTICATION_FAILED: 'Login failed. Username or password invalid',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  NOT_FOUND: 'The server has not found anything matching the Request-URI',
  FORBIDDEN: 'Authentication was provided, but the authenticated user is not permitted to perform the requested operation',
  UPDATE_SUCCESS: 'Update successfully!',
  MSG_USER_NOT_FOUND: 'Not found user',
  MSG_ALREADY_MIGRATE_DATA_USER: 'This user has already start revert user data',
  MSG_PROTECT_PWD_INVALID: 'Your entered verify_code is not valid'
};
