CREATE TABLE `report_cached_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_3rd` int(11) NOT NULL DEFAULT '0',
  `account_3rd_emails` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `account_type` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `storage` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `storage_total` bigint(20) unsigned NOT NULL,
  `groups` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `sub_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subs_type` int(11) DEFAULT NULL,
  `order_number` int(11) DEFAULT NULL,
  `subs_current_date` double(13,3) DEFAULT NULL,
  `last_used_date` double(13,3) DEFAULT NULL,
  `join_date` double(13,3) DEFAULT NULL,
  `next_renewal` double(13,3) DEFAULT NULL,
  `disabled` tinyint(1) unsigned DEFAULT '0',
  `deleted` tinyint(1) unsigned DEFAULT '0',
  `addition_info` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_migrate_status` tinyint(1) unsigned DEFAULT '1',
  `platform` json DEFAULT NULL,
  `old_platform` json DEFAULT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_email` (`email`) USING BTREE,
  KEY `idx_user_id` (`user_id`),
  KEY `idx_subID` (`sub_id`),
  KEY `idx_subs_type` (`subs_type`),
  KEY `idx_join_date` (`join_date`),
  KEY `idx_next_renewal` (`next_renewal`),
  KEY `idx_last_used_date` (`last_used_date`),
  KEY `idx_storage_total` (`storage_total`),
  FULLTEXT KEY `idx_groups` (`groups`),
  FULLTEXT KEY `idx_account_3rd_emails` (`account_3rd_emails`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci