
module.exports = {
  AccessTokenModel: require('./AccessTokenModel'),
  AdminServantManagerModel: require('./AdminServantManagerModel'),
  ApiLastModifiedModel: require('./ApiLastModifiedModel'),
  AddressbookModel: require('./AddressbookModel'),
  AdminPromotionModel: require('./AdminPromotionModel'),
  AppRegisterModel: require('./AppRegisterModel'),
  CalendarinstanceModel: require('./CalendarinstanceModel'),
  CalendarModel: require('./CalendarModel'),
  CollectionModel: require('./CollectionModel'),
  CollectionSystemModel: require('./CollectionSystemModel'),
  CollectionSystemUserGeneratedModel: require('./CollectionSystemUserGeneratedModel'),
  DeviceTokenModel: require('./DeviceTokenModel'),
  KanbanModel: require('./KanbanModel'),
  PrincipalModel: require('./PrincipalModel'),
  RestrictedUserModel: require('./RestrictedUserModel'),
  SettingModel: require('./SettingModel'),
  TimezoneModel: require('./TimezoneModel'),
  TrackingAppModel: require('./TrackingAppModel'),
  SubscriptionModel: require('./SubscriptionModel'),
  SubscriptionPurchaseModel: require('./SubscriptionPurchaseModel'),
  UrlModel: require('./UrlModel'),
  UserDeletedModel: require('./UserDeletedModel'),
  UserModel: require('./UserModel'),
  GroupModel: require('./GroupModel'),
  GroupUserModel: require('./GroupUserModel'),
  ReportCachedMigratedPlatformModel: require('./ReportCachedMigratedPlatformModel'),
  ReportCachedUsersModel: require('./ReportCachedUsersModel'),
  UserTrackingAppModel: require('./UserTrackingAppModel'),
  VirtualAliasModel: require('./VirtualAliasModel'),
  VirtualDomainModel: require('./VirtualDomainModel'),
  GlobalSettingModel: require('./GlobalSettingModel'),
  QuotaModel: require('./QuotaModel')
};

