pipeline {
    agent {
        label 'master'
    }
    environment {
        ECR_AHTH_LOGIN=sh(script: "aws ecr get-login --no-include-email --region us-east-1", returnStdout: true)
    }
    stages {
        stage('Build Image') {
            agent {
                label 'docker1.flodev.net'
            }
            steps {
                // sh 'docker stop daemon_notice_subs && docker rm daemon_notice_subs || echo "No existing daemon_notice_subs"'
                sh 'docker-compose build'
            }
        }
        stage('Ship to ECR') {
            agent {
                label 'docker1.flodev.net'
            }
            steps {
                sh '${ECR_AHTH_LOGIN}'
                sh 'docker tag daemon_notice_subs:latest 570744851573.dkr.ecr.us-east-1.amazonaws.com/flodaemon:daemon_notice_subs'
                sh 'docker push 570744851573.dkr.ecr.us-east-1.amazonaws.com/flodaemon:daemon_notice_subs'
            }
        }
        stage('FloDev') {
            agent {
                label 'docker1.flodev.net'
            }
            steps {
                sh '${ECR_AHTH_LOGIN}'
                // sh 'docker pull 570744851573.dkr.ecr.us-east-1.amazonaws.com/flodaemon:daemon_notice_subs'
                // sh 'docker stop daemon_notice_subs && docker rm daemon_notice_subs || echo \"No existing daemon_notice_subs\"'
                sh 'cd /home/docker/flodaemon && docker-compose up -d daemon_notice_subs'
            }
        }
        stage('FloUat') {
            agent {
                label 'docker1.flouat.net'
            }
            steps {
                sh '${ECR_AHTH_LOGIN}'
                sh 'docker pull 570744851573.dkr.ecr.us-east-1.amazonaws.com/flodaemon:daemon_notice_subs'
                // sh 'docker stop daemon_notice_subs && docker rm daemon_notice_subs || echo \"No existing daemon_notice_subs\"'
                sh 'cd /home/docker/flodaemon && docker-compose up -d daemon_notice_subs'
            }
        }
    }
}