class Criterion < ApplicationRecord
  EMAIL_TYPE = 1
  NOTE_TITLE = 2
  TODO_TITLE = 4
  EVENT_TITLE = 8
  EVENT_INVITEE = 16
  EVENT_LOCATION = 32
  URL_TYPE = 64
  CONTACT_COMPANY = 128
  CONTACT_DOMAIN = 256
  FILE_TYPE = 512
  CONTACT_NAME = 1024
end
