CREATE TABLE `cal_todo` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varbinary(1000) DEFAULT NULL,
  `calendarid` int(11) NOT NULL,
  `calendar_object_id` int(11) unsigned DEFAULT NULL,
  `uri` varbinary(1000) DEFAULT NULL,
  `star` tinyint(1) unsigned DEFAULT '0',
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_date` double(13,3) DEFAULT NULL,
  `due_date` double(13,3) DEFAULT NULL,
  `duration` bigint(20) DEFAULT '0',
  `subtasks` json DEFAULT NULL,
  `alert` json DEFAULT NULL,
  `stodo` tinyint(1) unsigned DEFAULT '0',
  `trashed` tinyint(1) DEFAULT '0',
  `repeat_rule` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recurid` double(13,3) DEFAULT NULL,
  `exdates` json DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'status of todo',
  `assigned` tinyint(1) DEFAULT '0' COMMENT 'Assign Todo',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_on_uid_and_calendarid_and_recurid` (`uid`,`calendarid`,`recurid`) USING BTREE,
  KEY `idx_is_trashed` (`trashed`) USING BTREE,
  KEY `idx_caltodo_uid` (`uid`) USING BTREE,
  KEY `idx_caltodo_calendarid_uri` (`calendarid`,`uri`) USING BTREE,
  KEY `fk_cal_todo_calendarobjectid_id` (`calendar_object_id`) USING BTREE,
  KEY `idx_caltodo_uri` (`uri`),
  FULLTEXT KEY `idx_caltodo_summary_description` (`summary`,`description`),
  CONSTRAINT `fk_cal_todo_calendarobjectid_id` FOREIGN KEY (`calendar_object_id`) REFERENCES `calendarobjects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC