CREATE TABLE `conference_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) NOT NULL,
  `invitee` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_number` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `start_time` double(13,3) NOT NULL DEFAULT '0.000' COMMENT 'start time of the call',
  `end_time` double(13,3) NOT NULL DEFAULT '0.000' COMMENT 'end time of the call',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '1 = video, 2 = audio ',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT 'the status of the call',
  `organizer` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attendees` text COLLATE utf8mb4_unicode_ci,
  `action_time` double(13,3) NOT NULL DEFAULT '0.000',
  `meeting_id` varchar(50) CHARACTER SET utf8mb4 NOT NULL,
  `external_meeting_id` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_reply` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = receive, 1 = reply',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `is_calling` tinyint(4) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_user_id_and_member_id` (`user_id`,`member_id`),
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_member_id` (`member_id`),
  KEY `idx_meeting_id` (`meeting_id`),
  KEY `conference_history_start_time_IDX` (`start_time`) USING BTREE,
  KEY `conference_history_phone_number_IDX` (`phone_number`) USING BTREE,
  KEY `idx_on_user_id_member_id_and_start_time` (`user_id`,`member_id`,`start_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'