CREATE TABLE `kanban` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `collection_id` bigint(20) unsigned NOT NULL,
  `name` varchar(5000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_number` decimal(20,10) DEFAULT '0.0000000000',
  `archive_status` int(5) DEFAULT '0',
  `order_kbitem` text COLLATE utf8mb4_unicode_ci,
  `order_update_time` double(13,3) NOT NULL DEFAULT '0.000',
  `show_done_todo` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `add_new_obj_type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sort_by_type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `archived_time` double(13,3) DEFAULT '0.000',
  `kanban_type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_trashed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_on_user_id_and_collection_id_and_updated_date` (`user_id`,`updated_date`,`collection_id`) USING BTREE,
  UNIQUE KEY `uniq_on_user_id_and_collection_id_and_order_number` (`user_id`,`collection_id`,`order_number`),
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_archive_status` (`archive_status`) USING BTREE,
  KEY `idx_collection_id` (`collection_id`) USING BTREE,
  KEY `idx_on_user_id_and_collection_id` (`user_id`,`collection_id`) USING BTREE,
  KEY `idx_kanban_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_name` (`name`(768))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8mb4_unicode_ci'