CREATE TABLE `realtime_message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL DEFAULT '0',
  `uid` varchar(300) NOT NULL,
  `code` varchar(100) NOT NULL,
  `from` varchar(100) NOT NULL,
  `type` enum('NOTIFICATION','EVENT','CHAT') NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `metadata` text NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `send_type` enum('CHANNEL','USER','BROADCAST') NOT NULL,
  `to_channel` varchar(300) DEFAULT NULL COMMENT 'channel name',
  `parent_uid` varchar(100) DEFAULT NULL,
  `qos` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0: only send 1 time, 1: alway send unit user readed',
  `delay` int(11) NOT NULL DEFAULT '0' COMMENT 'time second delay send',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1: sent; 0: unsend',
  `sent_time` double(13,3) DEFAULT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) NOT NULL,
  `deleted_date` double(13,3) DEFAULT NULL,
  `content_marked` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `message_marked` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `notification_UN` (`uid`),
  KEY `realtime_message_type_IDX` (`type`) USING BTREE,
  KEY `realtime_message_created_date_IDX` (`created_date`) USING BTREE,
  KEY `realtime_message_to_channel_IDX` (`to_channel`) USING BTREE,
  KEY `realtime_message_parent_uid_IDX` (`parent_uid`) USING BTREE,
  KEY `realtime_message_status_IDX` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1