CREATE TABLE `salt` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `created_date` double(13,3) DEFAULT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `salt0` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt1` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt2` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt3` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt4` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt5` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt6` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt7` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt8` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt9` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt10` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt11` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt12` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt13` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt14` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt15` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt16` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt17` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt18` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt19` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt20` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt21` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt22` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt23` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt24` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt25` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt26` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt27` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt28` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt29` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt30` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt31` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt32` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt33` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt34` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt35` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt36` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt37` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt38` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt39` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt40` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt41` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt42` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt43` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt44` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt45` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt46` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt47` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt48` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt49` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salt50` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='utf8_unicode_ci'