CREATE TABLE `setting` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `default_cal` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `timezone` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'America/Chicago',
  `tz_city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `working_time` json NOT NULL,
  `event_duration` int(11) NOT NULL DEFAULT '0',
  `alert_default` int(11) NOT NULL DEFAULT '0',
  `snooze_default` int(11) NOT NULL DEFAULT '15',
  `timezone_support` tinyint(4) NOT NULL DEFAULT '0',
  `task_duration` int(11) NOT NULL DEFAULT '0',
  `deadline` int(11) NOT NULL DEFAULT '0',
  `due_task` int(11) NOT NULL DEFAULT '0',
  `number_stask` int(11) NOT NULL DEFAULT '0',
  `total_duration` int(11) NOT NULL DEFAULT '0',
  `buffer_time` int(11) NOT NULL DEFAULT '0',
  `hide_stask` tinyint(4) NOT NULL DEFAULT '0',
  `background` int(11) NOT NULL DEFAULT '0',
  `short_duration` int(11) NOT NULL DEFAULT '30',
  `medium_duration` int(11) NOT NULL DEFAULT '60',
  `long_duration` int(11) NOT NULL DEFAULT '180',
  `default_folder` bigint(20) unsigned NOT NULL DEFAULT '0',
  `calendar_color` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `folder_color` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `navbar_system` text COLLATE utf8_unicode_ci NOT NULL,
  `navbar_custom` text COLLATE utf8_unicode_ci NOT NULL,
  `infobox` text COLLATE utf8_unicode_ci NOT NULL,
  `infobox_order` json NOT NULL,
  `contact_display_name` int(11) NOT NULL DEFAULT '0',
  `contact_display_inlist` int(11) NOT NULL DEFAULT '0',
  `m_ade` tinyint(4) NOT NULL DEFAULT '1',
  `m_event` tinyint(4) NOT NULL DEFAULT '1',
  `m_task` tinyint(4) NOT NULL DEFAULT '1',
  `m_stask` tinyint(4) NOT NULL DEFAULT '1',
  `m_done_task` tinyint(4) NOT NULL DEFAULT '1',
  `m_due_task` tinyint(4) NOT NULL DEFAULT '1',
  `m_note` tinyint(4) NOT NULL DEFAULT '1',
  `dw_due_task` tinyint(4) NOT NULL DEFAULT '1',
  `dw_ade` tinyint(4) NOT NULL DEFAULT '1',
  `dw_done_task` tinyint(4) NOT NULL DEFAULT '1',
  `dw_note` tinyint(4) NOT NULL DEFAULT '1',
  `del_warning` tinyint(4) NOT NULL DEFAULT '1',
  `hide_future_task` tinyint(4) NOT NULL DEFAULT '0',
  `ics_attachment` tinyint(4) NOT NULL DEFAULT '1',
  `mail_auto_download_check` int(11) NOT NULL DEFAULT '0',
  `mail_num_time_dont_auto_download` int(11) NOT NULL DEFAULT '6',
  `mail_time_dont_auto_download` int(11) NOT NULL DEFAULT '1',
  `mail_display_act_button` int(11) NOT NULL DEFAULT '0',
  `number_mail_lines_preview` int(11) NOT NULL DEFAULT '4',
  `mail_moving_check` int(11) NOT NULL DEFAULT '1',
  `mail_size_dont_download` int(11) NOT NULL DEFAULT '10',
  `show_nutshell` tinyint(4) NOT NULL DEFAULT '1',
  `show_bg_by_weather` tinyint(4) NOT NULL DEFAULT '0',
  `week_start` int(11) NOT NULL DEFAULT '0',
  `send_and_track` int(11) NOT NULL DEFAULT '2',
  `action_icon` int(11) NOT NULL DEFAULT '0',
  `emailbox_order` json NOT NULL,
  `alert_before` int(11) NOT NULL DEFAULT '60',
  `send_invite` tinyint(4) NOT NULL DEFAULT '0',
  `from_email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `default_alert_ade` int(11) DEFAULT '0',
  `default_alert_todo` int(11) DEFAULT '0',
  `default_milestone_alert` int(11) DEFAULT '0',
  `avatar` text COLLATE utf8_unicode_ci NOT NULL,
  `assign_tz_eve` tinyint(8) NOT NULL DEFAULT '1',
  `m_show` int(11) NOT NULL DEFAULT '23',
  `dw_show` int(11) NOT NULL DEFAULT '23',
  `agenda_show` int(11) NOT NULL DEFAULT '23',
  `move_email` int(11) NOT NULL DEFAULT '1',
  `noti_bear_track` int(11) NOT NULL DEFAULT '0',
  `state` int(11) NOT NULL DEFAULT '0',
  `recent_tz` text COLLATE utf8_unicode_ci,
  `order_url` mediumtext COLLATE utf8_unicode_ci,
  `order_todo` mediumtext COLLATE utf8_unicode_ci,
  `keep_state` mediumtext CHARACTER SET utf8mb4,
  `omni_cal_id` varchar(500) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `url_option` int(11) NOT NULL DEFAULT '0',
  `init_planner_st` int(11) NOT NULL DEFAULT '0',
  `order_storyboard` mediumtext COLLATE utf8_unicode_ci,
  `show_star` int(11) NOT NULL DEFAULT '0',
  `signature` text CHARACTER SET utf8mb4 NOT NULL,
  `filing_email` int(11) DEFAULT '0',
  `show_date_timezone` tinyint(4) DEFAULT '0',
  `show_feedback` tinyint(4) DEFAULT '1',
  `theme_mode` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0 (light - default), = 1: dark',
  `scroll_24h` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT 'Enable "Working Hour" mode',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `hide_done_todo` tinyint(1) NOT NULL DEFAULT '1',
  `indicate_done_todo` tinyint(1) NOT NULL DEFAULT '0',
  `note_ask` tinyint(1) NOT NULL DEFAULT '0',
  `todo_ask` tinyint(1) NOT NULL DEFAULT '0',
  `note_collection_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `todo_collection_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `notification_clean_date` int(11) NOT NULL DEFAULT '2592000' COMMENT 'DEFAULT: 43200 = 1 MONTH IN SECOND',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'