export enum ErrorCode {
  /**
   * HttpCode 400
   */
  BAD_REQUEST = 'badRequest',
  UNAUTHORIZED_REQUEST = 'unauthorizedRequest',
  VALIDATION_FAILED = 'validationFailed',
  INVALID_DATA = 'invalidData',
  SORT_OBJECT_IN_PROCESS = 'sortObjectInProgress',
  SORT_OBJECT_EXPIRED = 'sortObjectExpired',
  SORT_OBJECT_DUPLICATED = 'sortObjectDuplicated',
  SORT_OBJECT_DONE = 'sortObjectDone',
  SORT_OBJECT_RANGE_LIMIT_REACHED = 'sortObjectRangeLimitReached',
  SORT_OBJECT_INVALID_ATTRIBUTE = 'sortObjectInvalidObjectDataAttr',
  ORDER_NUMBER_OUT_OF_RANGE = 'orderNumberOutOfRange',
  UPDATE_FAILED = "updateFailed",
  DELETE_FAILED = "deleteFailed",
  MOVE_FAILED = "moveFailed",
  CREATE_FAILED = "createFailed",
  OBJECT_DUPLICATED = 'objectDuplicated',
  OBJECT_NOT_EXIST = 'objectNotExist',
  OBJECT_NOT_FOUND = 'objectNotFound',
  NOT_RELEASE_VERSION = 'notReleaseVersion',
  DEVICE_TOKEN_DOES_NOT_EXIST = 'deviceTokenDoesNotExist',
  CALENDAR_URI_DOES_NOT_EXIST = 'calendarUriDoesNotExist',
  METADATA_EMAIL_DOES_NOT_EXIST = 'metadataEmailDoesNotExist',
  TRACKING_DOES_NOT_EXIST = 'trackingDoesNotExist',
  NOTE_DOES_NOT_EXIST = 'noteDoesNotExist',
  INVALID_ACCOUNT_ID = 'invalidAccountId',
  INVALID_DES_ACCOUNT_ID = 'invalidDesAccountId',
  INVALID_SRC_ACCOUNT_ID = 'invalidSrcAccountId',
  INVALID_SUBCRIPTION = 'invalidSubcription',
  DUPLICATE_ENTRY = 'duplicateEntry',
  ALREADY_EXIST_DEVICE_TOKEN = 'alreadyExistDeviceToken',
  ADDRESS_BOOK_EXIST = 'addressBookExist',
  ADDRESS_BOOK_NOT_MULTI = 'addressBookNotMulti',
  SORT_OBJECT_IS_IN_DELETED_ITEM_COLLECTION = 'sortObjectIsInDeletedItemCollection',
  SORT_OBJECT_NOT_FOUND = 'sortObjectNotFound',
  ORDER_NUMBER_LENGTH_INVALID = 'orderNumberLengthInvalid',
  ORDER_NUMBER_ALREADY_EXIST = 'orderNumberAlreadyExist',
  ORDER_NUMBER_INVALID = 'orderNumberInvalid',
  INVALID_REQUEST_UID = 'invalidRequestUid',
  INVALID_APP_UID = 'invalidAppUid',
  CONFERENCE_NOT_EXIST = 'conferenceNotExist',
  CONFERENCE_NOT_PERMISSION = 'conferenceNotPermission',
  /**
   * HttpCode 404
   */
  INVITEE_NOT_FOUND = 'InviteeNotFound',
  CONTACT_NOT_FOUND = 'contactNotFound',
  ADDRESS_BOOK_NOT_FOUND = 'addressBookNotFound',
  SETTING_NOT_FOUND = 'settingNotFound',
  ACCOUNT_NOT_FOUND = 'accountNotFound',
  USER_NOT_FOUND = 'userNotFound',
  MEMBER_NOT_FOUND = 'memberNotFound',
  MEMBER_NOT_JOINED = 'memberNotJoined',
  EVENT_NOT_FOUND = "eventNotFound",
  CLOUD_NOT_FOUND = "cloudNotFound",
  URL_NOT_FOUND = "urlNotFound",
  RECENT_OBJ_NOT_FOUND = "recentObjectNotFound",
  SORT_ORDER_ITEM_NOT_FOUND = "sortOrderItemNotFound",
  FILE_NOT_FOUND = "fileNotFound",
  TODO_NOT_FOUND = "todoNotFound",
  PLATFORM_RELEASE_NOT_FOUND = "platformReleaseNotFound",
  HISTORY_NOT_FOUND = "historyNotFound",
  ROOMID_NOT_FOUND = "RoomIdNotFound",
  CALENDAR_URI_NOT_FOUND = 'calendarUriNotFound',
  OLD_CALENDAR_URI_NOT_FOUND = 'oldCalendarUriNotFound',
  COLLECTION_NOT_FOUND = 'collectionNotFound',
  COLLECTION_ID_INVALID = 'collectionIDInvalid',
  COLLECTION_NOT_EDIT_PER = 'collectionNotEditPer',
  COLLECTION_NOT_JOIN = 'collectionNotJoin',
  COLLECTION_SAME = 'collectionTheSame',
  PLATFORM_SETTING_NOT_FOUND = 'platformSettingNotFound',
  PLATFORM_SETTING_TAKEN = 'platformSettingTaken',
  DYNAMIC_KEY_BADKEY = 'dynamicKeyBadAppId',
  THIRD_PARTY_ACCOUNT = 'thirdPartyAccountNotFound',
  SYSTEM_NOT_FOUND = 'systemNotFound',
  CREDENTIAL_NOT_FOUND = 'credentialNotFound',
  SUGGESTED_NOT_FOUND = 'suggestedCollectionNotFound',
  /**
   * HttpCode 200
   */
  REQUEST_SUCCESS = "requestSuccess",
}