CREATE TABLE `cal_event` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varbinary(1000) DEFAULT NULL,
  `calendarid` int(11) NOT NULL,
  `calendar_object_id` int(11) unsigned DEFAULT NULL,
  `uri` varbinary(1000) DEFAULT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start` double(13,3) DEFAULT NULL,
  `end` double(13,3) DEFAULT NULL,
  `color` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allday` tinyint(1) DEFAULT '0',
  `timezone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alert` json DEFAULT NULL,
  `mi` tinyint(1) DEFAULT '0',
  `repeat_rule` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recurid` double(13,3) DEFAULT NULL,
  `exdates` json DEFAULT NULL,
  `trashed` tinyint(1) DEFAULT '0',
  `invitee_uid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_idx_cal_event_uid_calendarid_recurid` (`uid`,`calendarid`,`recurid`) USING BTREE,
  KEY `idx_is_trashed` (`trashed`),
  KEY `idx_calevent_uid` (`uid`),
  KEY `idx_calevent_calendarid_uri` (`calendarid`,`uri`),
  KEY `fk_cal_event_calendarobjectid_id` (`calendar_object_id`) USING BTREE,
  KEY `idx_calevent_uri` (`uri`),
  CONSTRAINT `fk_cal_event_calendarobjectid_id` FOREIGN KEY (`calendar_object_id`) REFERENCES `calendarobjects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci