// CHIME SERVICE
export const CHATTING_CREATE_CHANNEL = 'CHATTING_CREATE_CHANNEL';
export const CHATTING_DELETE_CHANNEL = 'CHATTING_DELETE_CHANNEL';
export const CHATTING_GENERATE_MEMBER = 'CHATTING_GENERATE_MEMBER';
export const CHATTING_CREATE_MEMBER = 'CHATTING_CREATE_MEMBER';
export const CHATTING_REMOVE_MEMBER = 'CHATTING_REMOVE_MEMBER';

// REAL TIME SERVICE
export const EVENT_TO_INDIVIDUAL = 'EVENT_TO_INDIVIDUAL';
export const NOTIFICATION_TO_INDIVIDUAL = 'NOTIFICATION_TO_INDIVIDUAL';
export const EVENT_TO_CHANNEL = 'EVENT_TO_CHANNEL';
export const NOTIFICATION_TO_CHANNEL = 'NOTIFICATION_TO_CHANNEL';
export const CREATE_REALTIME_CHANNEL = 'CREATE_REALTIME_CHANNEL';
export const DELETE_REALTIME_CHANNEL = 'DELETE_REALTIME_CHANNEL';
export const REMOVE_MEMBER_FROM_CHANNEL = 'REMOVE_MEMBER_FROM_CHANNEL';
export const ADD_MEMBER_TO_CHANNEL = 'ADD_MEMBER_TO_CHANNEL';

// SHARED COLLECTION
export const DECLINE_INVITE_COLLECTION = 'DECLINE_INVITE_COLLECTION';
export const INVITE_COLLECTION = 'INVITE_COLLECTION';
export const REMOVED_MEMBER_FROM_COLLECTION = 'REMOVED_MEMBER_FROM_COLLECTION';
export const MEMBER_LEAVE_COLLECTION = 'MEMBER_LEAVE_COLLECTION';
export const JOIN_COLLECTION = 'JOIN_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const TRASH_COLLECTION = 'TRASH_COLLECTION';
export const RECOVER_COLLECTION = 'RECOVER_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const CHANGE_ROLE_MEMBER_COLLECTION = 'CHANGE_ROLE_MEMBER_COLLECTION';
// COMMENT
export const ADD_COMMENT_COLLECTION = 'ADD_COMMENT_COLLECTION';
export const UPDATE_COMMENT_COLLECTION = 'UPDATE_COMMENT_COLLECTION';
export const DELETE_COMMENT_COLLECTION = 'DELETE_COMMENT_COLLECTION';
export const MENTION_COMMENT_COLLECTION = 'MENTION_COMMENT_COLLECTION';
// CONFERENCE
export const ADD_MEMBER_TO_CONFERENCE = 'ADD_MEMBER_TO_CONFERENCE';
export const REVOKE_MEMBER_FROM_CONFERENCE = 'REVOKE_MEMBER_FROM_CONFERENCE';
export const DELETE_CONFERENCE_CHANNEL = 'DELETE_CONFERENCE_CHANNEL';

// MEETING
export const SEND_MEETING_INVITE = 'SEND_MEETING_INVITE';
export const REPLY_MEETING_INVITE = 'REPLY_MEETING_INVITE';

// LINK OBJECT event
export const LINKED_OBJECT_SHARE_COLLECTION = 'LINKED_OBJECT_SHARE_COLLECTION';

// VCAL event
export const VCAL_SHARE_COLLECTION = 'VCAL_SHARE_COLLECTION';

// COMMENT
